### ISSUE TITLE
Flash message can hold up to 1514 characters

### ISSUE THREAD

**Issue by blueowlgreenfish** [davidpdrsn/axum-flash#13]
I'm facing a very strange issue.
When a flash message's length is less than 1515 characters, it goes through fine.
However, when it is more than 1514 characters, it won't go through.

Example below

**Sending flash message:**

    pub async fn send_flash_message(
        flash: Flash,
    ) -> Result<(Flash, Redirect), ResponseError> {
        Ok((
            flash.info("more than 1514 characters here"),
            Redirect::to("new-page"),
        ))
    }

**Receiving flash message:**

    pub async fn receive_flash_message(
        flashes: IncomingFlashes,
    ) -> Result<(IncomingFlashes, Html<String>), ResponseError> {
        // Do something with the flash message here
    }

The function for sending a flash message is triggered when a user submits a form, and the user will be redirected to `new-page`.
When the flash message contains less than 1515 characters, user gets redirected to  `new-page` **with the flash message**.
However, when the flash message contains more than 1514 characters, user gets redirected to `new-page` **without the flash message**.

I've tried setting `use_secure_cookies` to `false`, but it didn't do anything.
I've tested and observed the issue on both Firefox and Chrome.
My environment: rust 1.73.0, axum 0.6, axum-flash 0.7.

**Comment by davidpdrsn** [comment]
Probably a limit on the length of the cookie. The flash message is stored in a cookie.

**Comment by blueowlgreenfish** [comment]
I think you are right.
Does it mean there is nothing we can do?

**Comment by davidpdrsn** [comment]
Yep I’m afraid so. You could try to look for a way to compress the message.

1500 is quite a long message anyway.

**Comment by blueowlgreenfish** [comment]
Okay.
Thank you!
