### ISSUE TITLE
Error after upgrading Axum to 0.7

### ISSUE THREAD

**Issue by blueowlgreenfish** [davidpdrsn/axum-flash#14]
After upgrading Axum to 0.7, axum-flash gives the following error:

    the trait `FromRequestParts<()>` is not implemented for `IncomingFlashes`

**Comment by davidpdrsn** [comment]
axum-flash doesn't yet support axum 0.7 so you'll have to stick with 0.6 for now. I can probably publish an update later today.

**Comment by davidpdrsn** [comment]
I just published 0.8 which supports the latest axum.
