### ISSUE TITLE
Flash messages from axum middleware

### ISSUE THREAD

**Issue by tmazhuan** [davidpdrsn/axum-flash#9]
Hi, 

i'm writing a axum server where i implemented Authorization with sessions. Until now i did this in every handler.
Therefore i moved the check that user has as an active session into a middleware using from_fn. 
Everything works fine. The only problem i have is that i'm not able anymore to access Flash to send an info back to the browser in case the user is not authorized.
In the handlers i was using an  extractor, but in the middleware from_fn function this is not working anymore.
I assume this is because Flash is implementing FromRequestParts and not FromRequest.
I'm not sure if it is possible. But if it is, do you have a hint on how to implement it?
Thanks and best regards, Thomas

**Comment by davidpdrsn** [comment]
You need to use `from_fn_with_state` when creating the middleware. Here is an example:

```rust
use axum::{
    extract::FromRef,
    http::Request,
    middleware::{from_fn_with_state, Next},
    response::{IntoResponse, Redirect, Response},
    routing::get,
    Router,
};
use axum_flash::{Flash, IncomingFlashes, Key};

#[tokio::main]
async fn main() {
    let app_state = AppState {
        flash_config: axum_flash::Config::new(Key::generate()),
    };

    // the endpoints that requires auth
    let requires_auth = Router::new()
        .route("/foo", get(|| async {}))
        .layer(from_fn_with_state(app_state.clone(), auth_middleware));

    let app = Router::new()
        // `GET /` doesn't require because thats what our middleware
        // redirects to
        .route("/", get(root))
        .merge(requires_auth)
        .with_state(app_state);

    axum::Server::bind(&"0.0.0.0:3000".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}

#[derive(Clone, FromRef)]
struct AppState {
    flash_config: axum_flash::Config,
}

async fn root(flashes: IncomingFlashes) -> IncomingFlashes {
    flashes
}

async fn auth_middleware<B>(flash: Flash, request: Request<B>, next: Next<B>) -> Response {
    if authorized(&request) {
        next.run(request).await.into_response()
    } else {
        (flash.error("Unauthorized"), Redirect::to("/")).into_response()
    }
}

fn authorized<B>(request: &Request<B>) -> bool {
    // TODO: actually check auth
    false
}
```

**Comment by tmazhuan** [comment]
Hey David,
wow, incredible! Thanks very much for the quick answer! It works perfectly.
Best regards
